name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [18.15.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and Firebase Tools
        run: |
            npm install
            npm install -g firebase-tools
            firebase --version  # Add this line to check the version of Firebase Tools
  
      - name: Deploy to Firebase
        run: |
          firebase use default
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
